# Generated by Django 4.1.5 on 2023-02-18 13:02

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('file', models.FileField(upload_to=file.models.get_file_path)),
            ],
        ),
    ]
