version: "3.9"

services:
  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"

    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  backend:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    env_file: .env
    restart: always
    volumes:
      - .:/app/
      - media:/home/app/web/media
      - static:/home/app/web/static
    working_dir: "/app/"
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: ["gunicorn","--bind", "0.0.0.0:8000","automation_core.wsgi:application"]
    depends_on:
        db:
            condition: service_healthy

  nginx:
      build: ./docker/nginx
      volumes:
        - static:/home/app/web/static
        - media:/home/app/web/media
      ports:
        - 8001:80
      depends_on:
        - backend

volumes:
  mysql_data: 
  media:
  static: