# Generated by Django 4.1.3 on 2022-12-26 13:35

import auto.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=auto.models.get_random_id, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('SN', 'SEEN'), ('US', 'UNSEEN')], max_length=115)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='departman',
            name='user',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='departman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.departman'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='has_message',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to=auto.models.get_image_path),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='rank',
            field=models.CharField(choices=[('MAN', 'MANAGER'), ('SUP', 'SUPERWISER'), ('STF', 'STAFF')], default=('STF', 'STAFF'), max_length=115),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='id',
            field=models.CharField(default=auto.models.get_random_id, editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='departman',
            name='id',
            field=models.CharField(default=auto.models.get_random_id, editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.CharField(default=auto.models.get_random_id, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('priority', models.CharField(choices=[('H', 'HIGH'), ('M', 'MIDIUM'), ('L', 'LOW')], default=('M', 'MIDIUM'), max_length=115)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('departman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.departman')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.CharField(default=auto.models.get_random_id, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=115)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('departman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.departman')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileHistory',
            fields=[
                ('id', models.CharField(default=auto.models.get_random_id, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to=auto.models.get_image_path)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('history', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_file', to='auto.history')),
            ],
        ),
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=auto.models.get_image_path)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_file', to='auto.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auto.letter'),
        ),
        migrations.AddField(
            model_name='comment',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
