# Generated by Django 4.1.3 on 2022-11-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_ticket_remove_departman_user_baseuser_departman_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmessage',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
