# Generated by Django 4.1.7 on 2023-03-16 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto', '0002_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Profile',
        ),
    ]
