# Generated by Django 4.1.3 on 2022-11-17 08:02

import auto.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_ticket_ticketmessage_tickethistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=auto.models.get_image_path)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.ticketmessage')),
            ],
        ),
    ]
