# Generated by Django 4.1.3 on 2022-12-27 08:33

import auto.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_baseuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(default='+914000000', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='letter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auto.letter'),
        ),
        migrations.AlterField(
            model_name='commentfile',
            name='file',
            field=models.FileField(default='def.jpg', upload_to=auto.models.get_image_path),
        ),
    ]
