# Generated by Django 4.1.3 on 2022-11-18 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_rename_create_at_ticketmessage_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sender',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='has_message',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='rank',
            field=models.CharField(choices=[('MAN', 'MANAGER'), ('SUP', 'SUPERWISER'), ('STF', 'STAFF')], default='STF', max_length=115),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='reciever',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='status',
            field=models.CharField(choices=[('SN', 'SEEN'), ('US', 'UNSEEN')], default=1, max_length=115),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='departman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.departman'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.departman'),
        ),
    ]
