# Generated by Django 4.1.7 on 2023-03-18 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='Archive',
        ),
        migrations.RenameModel(
            old_name='FileHistory',
            new_name='ArchiveFile',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='CommentFile',
            new_name='MessageFile',
        ),
    ]
