# Generated by Django 4.1.3 on 2022-11-18 08:17

import auto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_alter_tickethistory_options_remove_ticket_reciever_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='id',
            field=models.CharField(default=auto.models.get_random_id, editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='departman',
            name='id',
            field=models.CharField(default=auto.models.get_random_id, editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(default=auto.models.get_random_id, editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='id',
            field=models.CharField(default=auto.models.get_random_id, editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='id',
            field=models.CharField(default=auto.models.get_random_id, editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
