# Generated by Django 4.1.3 on 2022-12-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_baseuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departman',
            old_name='discription',
            new_name='description',
        ),
    ]
