# Generated by Django 4.1.3 on 2022-11-23 05:31

import auto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_alter_ticket_options_alter_baseuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to=auto.models.get_image_path),
        ),
    ]
