# Generated by Django 4.1.3 on 2023-01-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_letter_title_alter_baseuser_departman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='commentfile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='filehistory',
            options={'ordering': ['-created_at']},
        ),
    ]
