# Generated by Django 4.1.7 on 2023-03-19 03:37

import auto.path_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_rename_history_archivefile_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=auto.path_generator.profile_image_upload),
        ),
    ]
