# Generated by Django 4.1.3 on 2022-12-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_rename_reciever_ticketmessage_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmessage',
            old_name='discription',
            new_name='description',
        ),
    ]
