# Generated by Django 4.1.3 on 2022-12-06 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_rename_discription_ticketmessage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='ticket_message',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_upload', to='auto.ticketmessage'),
        ),
    ]
