# Generated by Django 4.1.5 on 2023-02-17 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_alter_baseuser_image_alter_commentfile_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='owner',
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='letter_receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letter',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
