# Generated by Django 4.1.5 on 2023-02-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_remove_letter_owner_letter_receiver_letter_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('c', 'close'), ('o', 'open')], default=('o', 'o'), max_length=25),
        ),
    ]
