# Generated by Django 4.1.7 on 2023-03-16 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('chf', 'chief'), ('man', 'manager'), ('emp', 'employee')], max_length=25)),
                ('has_message', models.PositiveIntegerField(default=0)),
                ('photo', models.CharField(max_length=512)),
                ('departman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.departman')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
